name: Pulumi Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set the required node version for your Pulumi program

    # Step 3: Install Pulumi CLI
    - name: Install Pulumi CLI
      run: |
        curl -fsSL https://get.pulumi.com | sh
        export PATH=$HOME/.pulumi/bin:$PATH

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        npm install

    # Step 5: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your AWS region if necessary

    # Step 6: Run Pulumi to deploy infrastructure
    - name: Run Pulumi up
      run: |
        pulumi login  # Log in to Pulumi
        pulumi stack select your-stack-name  # Replace with your Pulumi stack name
        pulumi up --yes  # Run Pulumi to deploy resources

    # Step 7: Output the URLs for the S3 bucket and CloudFront distribution
    - name: Output URLs
      run: |
        echo "S3 Bucket URL: ${{ steps.s3-output.outputs.bucket-url }}"
        echo "CloudFront URL: ${{ steps.cloudfront-output.outputs.cloudfront-url }}"
