name: Pulumi Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Pulumi CLI
    - name: Install Pulumi CLI
      if: env.changed == 'true'
      run: |
        curl -fsSL https://get.pulumi.com | sh
        export PATH=$HOME/.pulumi/bin:$PATH

    # Step 3: Install dependencies
    - name: Install dependencies
      if: env.changed == 'true'
      run: npm install

    # Step 4: Configure AWS credentials
    - name: Configure AWS credentials
      if: env.changed == 'true'
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your AWS region

    # Step 5: Run Pulumi deployment (only if YAML changed)
    - name: Pulumi up
      if: env.changed == 'true'
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      run: pulumi up --yes

    # Step 6: Skip deployment message
    - name: No changes detected
      if: env.changed == 'false'
      run: echo "No changes detected in Pulumi.yaml. Skipping deployment."
